services:
  banner-service:
    container_name: banner-service
    build: ../banner-service
    ports:
      - "80:80"
    restart: always
    volumes:
      - /root/site/frame:/banners
      - /root/site/plate:/plates
  banner-random:
    container_name: banner-random
    image: banner-random

    restart: always
    environment:
      - PORT=2020
      - FOLDER_NAME=/banners
    volumes:
      - /root/site/frame:/banners
  collection-showcase:
    container_name: collection-showcase
    image: collection-showcase
    environment:
      - FRAME_PATH=/_banners
      - PLATE_PATH=/_plates
    volumes:
      - /root/site/frame:/_banners
      - /root/site/plate:/_plates
  svelteway:
    container_name: svelteway
    image: svelteway:latest
    restart: always
    environment:
      - STEAM_API_KEY=
  copyparty:
    container_name: copyparty
    image: copyparty/ac
    ports:
      - "3923:3923"
    restart: always
    volumes:
      - /root/site:/w
      - /root/copyparty:/cfg
