services:
  svelteway-nginx:
    container_name: svelteway-nginx
    image: ghcr.io/baconway/svelteway-nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - /root/site/sdez:/sdez
      - /root/site/sdga:/sdga

  svelteway-db:
    container_name: collection_db
    image: postgres:18-alpine
    volumes:
      - /root/site/svelteway-db/postgres:/var/lib/postgresql

  banner-random:
    container_name: banner-random
    build: /root/site/banner-random
    restart: always
    environment:
      - PORT=2020
      - FOLDER_NAME=/banners
    volumes:
      - /root/site/sdga/frame:/banners

  svelteway-collection-showcase:
    profiles: ["debug", "testing"]
    container_name: svelteway-collection-showcase
    image: svelteway-collection-showcase:latest
    environment:
      - HOST=svelteway-db
      - DB_USER=Baconway
      - PORT=5432
      - DB=sveltewayDB
      - PASSWORD=bwaydatabase

  svelteway:
    container_name: svelteway
    image: ghcr.io/baconway/svelteway:latest
    restart: always
    environment:
      - STEAM_API_KEY=

  copyparty:
    container_name: copyparty
    image: copyparty/ac
    ports:
      - "3923:3923"
    restart: always
    volumes:
      - /root/site:/w
      - /root/copyparty:/cfg
